### ISSUE TITLE
I keep getting an error when I try to run the captioner. 

### ISSUE THREAD

**Issue by Alpha-Leader** [LarryJane491/Image-Captioning-in-ComfyUI#4]
![Caption Error](https://github.com/LarryJane491/Image-Captioning-in-ComfyUI/assets/5894213/849cacba-0681-44fd-990c-2e9bae49950a)

I am not sure why this wont work. Fresh install of ComfyUI too.

**Comment by Alpha-Leader** [comment]
The WD tagger on its own works fine if I plug an image into it, but for some reason I get this error when I have your node plugged into it, or anything else that uses the image connector.

**Comment by LarryJane491** [comment]
Hey there! If you unplug WD, does the Show Text node work? It should give the name of all png files. I ask to know if there is a problem with the node itself or with the connection to WD ^^.

**Comment by Alpha-Leader** [comment]
When don't plug in WD I get this error.
![error 2](https://github.com/LarryJane491/Image-Captioning-in-ComfyUI/assets/5894213/35bec059-3021-4b20-a442-6fd5aa9881fa)

**Comment by JohnnyJae** [comment]
> When don't plug in WD I get this error. ![error 2](https://private-user-images.githubusercontent.com/5894213/309020941-35bec059-3021-4b20-a442-6fd5aa9881fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MDU5NDMsIm5iZiI6MTcwOTQwNTY0MywicGF0aCI6Ii81ODk0MjEzLzMwOTAyMDk0MS0zNWJlYzA1OS0zMDIxLTRiMjAtYTQ0Mi02ZmQ1YWE5ODgxZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDJUMTg1NDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTZiNjYxMmQ3ZDEzZTNiYTYyOTRkMjVjMGQ2M2Q1OGJiMDFmMmRiNzVmMjRjM2U3NTIxZDkxNTE5OGRmNDNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M9u6xU4k29t4a7BMfvqaUHUr_SaTOjyVgsonMe4MG3A)

I got this error when trying to use .jpg files. It works if you convert them to png

**Comment by liusida** [comment]
Same here.

```
!!! Exception during processing!!! list index out of range
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI-WD14-Tagger\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI-WD14-Tagger\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI-WD14-Tagger\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI-WD14-Tagger\custom_nodes\Image-Captioning-in-ComfyUI\LoRAcaption.py", line 53, in save_text_file
    filename = self.generate_filename(path, namelistsplit, file_extension)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI-WD14-Tagger\custom_nodes\Image-Captioning-in-ComfyUI\LoRAcaption.py", line 65, in generate_filename
    filename = f"{namelistsplit[counter-1]}{extension}"
                  ~~~~~~~~~~~~~^^^^^^^^^^^
IndexError: list index out of range
```

This is caused by running the workflow twice. Since all .txt files are already generated, the loop goes wrong:
```
        while os.path.exists(os.path.join(path, filename)):
            counter += 1
            filename = f"{namelistsplit[counter-1]}{extension}"
```

**Comment by liusida** [comment]
I've digged into this issue deeper, and I found another issue:

say, i have 2 pictures, `1.png` is a cat, and `2.png` is a dog. If for some reason there exists a `1.txt`, then `cat` will be written to `2.txt` and this `list index out of range` error will occur.
